### PR TITLE
Updated inheritance

### PR DESCRIPTION
**Pull request by Lynxes**
## Have you tested it?
- [x] I have not tested it.
...

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
**STOP COMMITTING ON GITHUB**

The repo is already spammy enough they dont need like 6 commits for changing some inheritence

**Comment by Lynxes** [comment]
chill out bruh i cant commit everything at once anyway

**Comment by TheDiamondYT1** [comment]
@Lynxes Yes you can. Its called [Git](https://git-scm.com).

**Comment by NFGamerMC** [comment]
@TheDiamondYT1 Lol, also @Lynxes try GitKraken it seems to be more user friendly and speedy

**Pull request merged**
